name: 'Build wheels'
description: 'Build Python package wheels using cibuildwheel.'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6

    - name: Build wheels
      # Configuration of cibuildwheel is done in pyproject.toml
      uses: pypa/cibuildwheel@v3.3.1

    - name: Upload artefact
      uses: actions/upload-artifact@v6
      with:
        path: ./wheelhouse/*.whl
