name: 'Build sdist'
description: 'Build Python package source distribution and wheels.'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6

    - name: Build sdist
      shell: bash
      run: pipx run build

    - name: Upload artifact
      uses: actions/upload-artifact@v6
      with:
        path: dist/*
