name: 'Build Sphinx Docs'
description: 'Builds sphinx docs and publishes them to GitHub Pages'

inputs:
  python-version:
    description: 'Python version'
    required: false
    type: string
    default: '3.x'
  check-links:
    description: 'Check links'
    required: false
    type: boolean
    default: true

runs:
  using: 'composite'
  steps:
  - uses: actions/checkout@v4

  - name: Setup Python
    uses: actions/setup-python@v5
    with:
      python-version: ${{ inputs.python-version }}

  - name: Upgrade pip
    shell: bash
    run: |
      # install pip=>20.1 to use "pip cache dir"
      python3 -m pip install --upgrade pip

  - name: Get pip cache dir
    shell: bash
    id: pip-cache
    run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

  - name: Cache dependencies
    uses: actions/cache@v4
    with:
      path: ${{ steps.pip-cache.outputs.dir }}
      key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      restore-keys: |
        ${{ runner.os }}-pip-

  - name: Install dependencies
    shell: bash
    run: python3 -m pip install -r ./docs/requirements.txt

  - name: Check links
    if: ${{ inputs.check-links == 'true' }}
    shell: bash
    run: sphinx-build docs/source docs/build -b linkcheck

  # needs to have sphinx.ext.githubpages in conf.py extensions list
  - name: Building documentation
    shell: bash
    run: sphinx-build docs/source docs/build -b html

  - name: Upload the content for deployment
    uses: actions/upload-artifact@v4
    with:
      name: docs-build
      path: ./docs/build/
