name: 'Upload packages to PyPI'
description: 'Upload built packages to the Python Package Index (PyPI).'

inputs: 
  secret-pypi-key:
    description: 'API key for publishing to PyPI'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: artifact
        path: dist
    - uses: pypa/gh-action-pypi-publish@v1.8.14
      with:
        user: __token__
        password: ${{ inputs.secret-pypi-key }}
