name: 'Deploy Sphinx Docs'
description: 'Deploys pre-built sphinx docs on GitHub Pages'

inputs: 
  secret_input:
    description: 'The secret input for the GitHub token'
    required: true
  use-make:
    description: |
      Specify whether `make` is used in the `build_sphinx_docs` action,
      so that the correct publish directory is used
    required: false
    type: boolean
    default: false

runs:
  using: 'composite'
  steps:
  - name: Checkout repository
    uses: actions/checkout@v6

  - name: Clear previous build if present
    shell: bash
    run: rm -rf ./docs/build

  - name: Download the content for deployment
    uses: actions/download-artifact@v6
    with:
      name: docs-build
      path: ./docs/build

  - name: Deploy
    env: 
      GITHUB_TOKEN: ${{ inputs.secret_input }}
    uses: peaceiris/actions-gh-pages@v4
    with:
      github_token: ${{ env.GITHUB_TOKEN }}
      publish_dir: ${{ inputs.use-make == 'true' && './docs/build/html' || './docs/build/' }}
