name: 'Deploy Sphinx Docs'
description: 'Deploys pre-built sphinx docs on GitHub Pages'

inputs: 
  secret_input:
    description: 'The secret input for the GitHub token'
    required: true
  use-make:
    description: |
      Specify whether `make` is used in the `build_sphinx_docs` action,
      so that the correct publish directory is used
    required: false
    type: boolean
    default: false
  use-artifactci:
    description: |
      Specify whether the artifact was uploaded by artifact.ci,
      to ensure that its contents are moved to the correct publish directory
    required: false
    type: boolean
    default: false

runs:
  using: 'composite'
  steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Clear previous build if present
    shell: bash
    run: rm -rf ./docs/build

  - name: Download the content for deployment
    uses: actions/download-artifact@v4
    with:
      name: docs-build
      path: ./docs/build

  # If this was downloaded from artifact.ci, the content will be nested
  # in ./docs/build/docs/build/, so we need to fix that.
  - name: Move the content to the correct directory
    if: ${{ inputs.use-artifactci == 'true' }}
    shell: bash
    run: |
      mv ./docs/build/docs/build/* ./docs/build/
      rm -rf ./docs/build/docs

  - name: Deploy
    env: 
      GITHUB_TOKEN: ${{ inputs.secret_input }}
    uses: peaceiris/actions-gh-pages@v4
    with:
      github_token: ${{ env.GITHUB_TOKEN }}
      publish_dir: ${{ inputs.use-make == 'true' && './docs/build/html' || './docs/build/' }}
