name: 'Check manifest'
description: 'Check Python package manifest'

inputs:
  python-version:
    description: 'Python version'
    required: false
    type: string
    default: '3.x' # use x-ranges to specify the latest stable version of Python (for specified major version)

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install check-manifest
    - name: Check Manifest
      shell: bash
      run: check-manifest
